# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netdevice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipv4_address',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='ipv6_address',
            name='interface',
        ),
        migrations.DeleteModel(
            name='ipv4_address',
        ),
        migrations.DeleteModel(
            name='ipv6_address',
        ),
    ]
