# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 14:10
from __future__ import unicode_literals

from django.db import migrations

def create_network_os(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    network_os = apps.get_model('netdevice', 'network_os')
    network_os.objects.get_or_create(name='ios')
    network_os.objects.get_or_create(name='junos')
    network_os.objects.get_or_create(name='bird')
    network_os.objects.get_or_create(name='quagga')
    network_os.objects.get_or_create(name='yaml')

class Migration(migrations.Migration):

    dependencies = [
        ('netdevice', '0002_auto_20180511_0619'),
    ]

    operations = [
        migrations.RunPython(create_network_os),
    ]
