# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-10 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netdevice', '0006_auto_20190409_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vrf',
            old_name='vrf_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vrf',
            old_name='vrf_target',
            new_name='target',
        ),
    ]
