# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_gen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='router',
        ),
        migrations.RemoveField(
            model_name='ipv4_address',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='ipv4_static',
            name='router',
        ),
        migrations.RemoveField(
            model_name='ipv6_address',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='ipv6_static',
            name='router',
        ),
        migrations.RemoveField(
            model_name='logical_interface',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='aut_num',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='router',
        ),
        migrations.RemoveField(
            model_name='router',
            name='local_aut_num',
        ),
        migrations.RemoveField(
            model_name='router',
            name='network_os',
        ),
        migrations.DeleteModel(
            name='aut_num',
        ),
        migrations.DeleteModel(
            name='interface',
        ),
        migrations.DeleteModel(
            name='ipv4_address',
        ),
        migrations.DeleteModel(
            name='ipv4_static',
        ),
        migrations.DeleteModel(
            name='ipv6_address',
        ),
        migrations.DeleteModel(
            name='ipv6_static',
        ),
        migrations.DeleteModel(
            name='logical_interface',
        ),
        migrations.DeleteModel(
            name='neighbor',
        ),
        migrations.DeleteModel(
            name='network_os',
        ),
        migrations.DeleteModel(
            name='router',
        ),
    ]
