# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netdevice', '0001_initial'),
        ('bgp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdevice.router'),
        ),
    ]
