# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdevice', '0006_auto_20190409_0325'),
        ('bgp', '0003_auto_20190328_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aut_num',
            name='asn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='aut_num',
            unique_together=set([('asn', 'vrf')]),
        ),
    ]
