# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-28 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vrf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrf_name', models.CharField(max_length=255)),
                ('vrf_target', models.CharField(max_length=255)),
            ],
        ),
    ]
