# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netdevice', '0002_auto_20180511_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipv4_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(unpack_ipv4=True)),
                ('cidr', models.PositiveSmallIntegerField(default=24)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netdevice.logical_interface')),
            ],
        ),
        migrations.CreateModel(
            name='ipv6_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('cidr', models.PositiveSmallIntegerField(default=64)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netdevice.logical_interface')),
            ],
        ),
    ]
