# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aut_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='neighbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('soft_inbound', models.BooleanField()),
                ('aut_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.aut_num')),
            ],
        ),
        migrations.CreateModel(
            name='network_os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_id', models.GenericIPAddressField(unpack_ipv4=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ibgp', models.BooleanField()),
                ('network_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.network_os')),
            ],
        ),
    ]
