# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.router'),
        ),
    ]
