# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aut_num',
            name='asn',
            field=models.BigIntegerField(),
        ),
    ]
