# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logical_interface',
            name='ldp',
            field=models.BooleanField(default=False),
        ),
    ]
