# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipv4_address',
            old_name='interface',
            new_name='parent_interface',
        ),
        migrations.RenameField(
            model_name='ipv6_address',
            old_name='interface',
            new_name='parent_interface',
        ),
    ]
