# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0002_auto_20180504_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipv4_address',
            old_name='parent_interface',
            new_name='interface',
        ),
        migrations.RenameField(
            model_name='ipv6_address',
            old_name='parent_interface',
            new_name='interface',
        ),
    ]
