# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0002_logical_interface_ldp'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='local_aut_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='op_webgui.aut_num'),
        ),
    ]
