# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0003_auto_20160806_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.router')),
            ],
        ),
    ]
