# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0005_interface_mtu'),
    ]

    operations = [
        migrations.CreateModel(
            name='logical_interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mtu', models.BigIntegerField(default=1500)),
                ('vlan', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interface',
            name='mtu',
            field=models.BigIntegerField(default=1514),
        ),
        migrations.AddField(
            model_name='logical_interface',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.interface'),
        ),
    ]
