# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0006_auto_20180510_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipv4_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField(unpack_ipv4=True)),
                ('cidr', models.PositiveSmallIntegerField(default=24)),
                ('next_hop', models.GenericIPAddressField(unpack_ipv4=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.router')),
            ],
        ),
        migrations.CreateModel(
            name='ipv6_static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField()),
                ('cidr', models.PositiveSmallIntegerField(default=64)),
                ('next_hop', models.GenericIPAddressField(unpack_ipv4=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.router')),
            ],
        ),
    ]
