# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0007_ipv4_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipv6_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('cidr', models.PositiveSmallIntegerField(default=24)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='op_webgui.logical_interface')),
            ],
        ),
    ]
