# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0009_auto_20180502_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='logical_interface',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
