# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0010_auto_20180503_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv6_address',
            name='cidr',
            field=models.PositiveSmallIntegerField(default=64),
        ),
    ]
