# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 05:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0013_logical_interface_physical_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logical_interface',
            name='vlan',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4096)]),
        ),
    ]
