# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0014_auto_20180503_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='dot1q',
            field=models.BooleanField(default=False),
        ),
    ]
