# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0015_interface_dot1q'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='service_netconf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='router',
            name='service_ssh',
            field=models.BooleanField(default=True),
        ),
    ]
