# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('op_webgui', '0017_auto_20180504_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4_address',
            name='interface',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='op_webgui.logical_interface'),
        ),
        migrations.AlterField(
            model_name='ipv6_address',
            name='interface',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='op_webgui.logical_interface'),
        ),
    ]
